seed: 123

log:
  filename: train.log

dataset:
  text_dir: data/summary
  label_dir: data/label_level2
  batch_size: 32

method: Transformers

trainer:
  max_epochs: -1
  min_epochs: 500
  accumulate_grad_batches: 8

model:
  model_name: cl-tohoku/bert-base-japanese-v2
  optimizer: Ranger
  learning_rate: 1.0e-3

early_stopping:
  monitor: train_loss
  mode: min
  patience: 100
