seed: 123

log:
  filename: train.log

dataset:
  text_dir: data/texts
  label_dir: data/label_level1

method: TransformerClassifier
add_special_token: true

train:
  batch_size: 8
  max_epochs: 10000
  min_epochs: null

model:
  mode: mean
  emb_size: 16
  nhead: 2
  nlayers: 1
  hidden_dim: 64
  drop_rate: 0.25
  optimizer: RAdam
  learning_rate: 1.0e-3
  T_max: null

early_stopping:
  monitor: train_loss
  mode: min
  patience: 100
